name: build-and-push-image
on:
  push:
    branches:
      - master
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      registry-type: ghcr.io
    strategy:
      matrix:
        build-platform: ["linux/amd64","linux/arm64"]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.registry-type }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
        with:
          platform: ${{ matrix.build-platform }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{env.registry-type}}/lonecalvary78/ant-tooklit:11
